name: CI Workflow – "Student Registry" App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Use the latest Node.js version
      
      - name: Install dependencies
        run: npm ci  # Install dependencies using package-lock.json
      
      - name: Run tests
        run: npm test  # Run the default test script

      # Optional: Uncomment if you have a test-unit script
      # - name: Run unit tests
      #   run: npm run test-unit  # Ensure this script exists in package.json
